Feat/basetypes
onebeyond/monaco pull request #11
Opened 2022-11-18 18:49 UTC by Ture2

To work better with Enumeration types and DTOs I've added a class to better with and not repeat code.

2022-11-18 18:55 UTC, CesarD commented on src/Content/Monaco.Template.Common.Application/Monaco.Template.Common.Application.csproj
> +    <ProjectReference Include="..\Monaco.Template.Common.Domain\Monaco.Template.Common.Domain.csproj" />
You don't need this reference because it already exists by transitivity because of `Monaco.Template.Common.Infrastructure`.

```suggestion
```

2022-11-18 18:57 UTC, CesarD commented on src/Content/Monaco.Template.Common.Application/DTOs/Extensions/BaseTypeExtensions.cs
> +		where TEntity : Enumeration, IReferential
I think you can spare the `IReferential` constraint, to be able to do this for *any* `Enumeration` entity, not only those that are also implementing `IReferential`.

```suggestion
		where TEntity : Enumeration
```

2023-01-09 19:51 UTC, Ture2 commented
Updated

2023-01-10 10:15 UTC, CesarD requested changes

2023-01-10 10:15 UTC, CesarD commented on src/Content/Monaco.Template.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Monaco.Template.Common. Application.Tests", "Monaco.Template.Common. Application.Tests\Monaco.Template.Common. Application.Tests.csproj", "{93ECBA
Please fix the typo once the path has been corrected at file system.

```suggestion
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Monaco.Template.Common.Application.Tests", "Monaco.Template.Common.Application.Tests\Monaco.Template.Common.Application.Tests.csproj", "{93ECBA58-111C-401F-AA51-45626772E14A}"
```

2023-01-10 10:15 UTC, CesarD commented on src/Content/Monaco.Template.Common. Application.Tests/EnumerationTests.cs
> +namespace Monaco.Template.Common._Application.Tests;
```suggestion
namespace Monaco.Template.Common.Application.Tests;
```

2023-01-10 10:15 UTC, CesarD commented on src/Content/Monaco.Template.Common. Application.Tests/Monaco.Template.Common. Application.Tests.csproj
> +        <RootNamespace>Monaco.Template.Common._Application.Tests</RootNamespace>
```suggestion
```

2024-02-05 11:13 UTC, closed without merging